# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_converter:
    enabled: true
  view:
    view_response_listener: true
    formats: { json: true, xml: false, rss: false }
  serializer:
    serialize_null: true
  format_listener:
    enabled: true
    rules:
      - { path: '^/api', prefer_extension: true, fallback_format: 'json', priorities: [ 'json', 'html' ] }
      - { path: '^/',  stop: true }
  param_fetcher_listener:  force
  exception:
    #enabled: true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.

