nelmio_api_doc:
    documentation:
        info:
            title: Star Trek API
            description: This is an fantastic app!
            version: 1.0.0
        components:
            schemas:
                Error:
                    description: "Error"
                    type: object
                    properties:
                        code:
                            type: integer
                            format: int32
                            example: 404
                        message:
                            type: string
                            example: Item not found
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc(\.json)?$) # Accepts routes under /api except /api/doc
    models:
        names:
            - { alias: Serie, type: App\Entity\Serie, groups: [detail]}
            - { alias: Serie_light, type: App\Entity\Serie, groups: [list]}
